name: Build
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Checkout repository
      uses: actions/checkout@v1

    - name: Build
      run: go build -v -o build/gateway .

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@v1

    - name: Login to Docker
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    - name: Build image
      run: docker build .

    - name: Push
      run: docker push spectacles/gateway:$(echo $GITHUB_REF | cut -d / -f 3)
